<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DirectorySorter.Core</AssemblyName>
    <RootNamespace>DirectorySorter.Core</RootNamespace>
  </PropertyGroup>
</Project>
